[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tokens_nft = "ErCVP1SCdhdm55EKJNp9DV2rdcBvneSH6Lf29KxVyB7H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
